name: directus
description: The unofficial SDK for Directus, with REST API and auth. Compatible with Flutter.
version: 0.2.2
homepage: https://www.directus.io
repository: https://github.com/apstanisic/directus-dart
issue_tracker: https://github.com/apstanisic/directus-dart/issues

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  # Http client
  dio: ^3.0.0
  # Storage
  shared_preferences: ">=0.5.12+4 <2.0.0"
  # Annotations
  meta: 1.3.0-nullsafety.6
  # Used for decorators for JSON serialization
  json_annotation: ^4.0.0-nullsafety.0
  # We need Flutter because `shared_preferences` does not work without
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.13
  mockito: ^5.0.0-nullsafety.0
  build_runner: ^1.10.11
  json_serializable: ^4.0.0-nullsafety.0
