name: directus
description: The unofficial SDK for Directus, with REST API and auth. Compatible with Flutter.
version: 0.6.2
homepage: https://www.directus.io
repository: https://github.com/apstanisic/directus-dart
issue_tracker: https://github.com/apstanisic/directus-dart/issues

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  # Http client
  dio: ^4.0.0
  # Storage
  shared_preferences: ^2.0.8
  # Annotations
  meta: ^1.7.0
  # Used for decorators for JSON serialization
  json_annotation: ^4.1.0
  # We need Flutter because `shared_preferences` does not work without it
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.12
  mockito: ^5.0.16
  json_serializable: ^6.1.4
  build_runner: ^2.1.2
  lints: ^1.0.1
