name: directus_core_example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  directus_core:
    path: ../

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
