name: directus_core_example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  directus_core: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
